### ISSUE TITLE
convert to react component

### ISSUE THREAD

**Issue by safeimuslim** [SamHerbert/SVG-Loaders#18]
Hi Sam, 

May i convert SVG-Loaders to react component ?  and i will publish to github ?

BGD
Safei Muslim

**Comment by SamHerbert** [comment]
Hey Safei,

Feel free to create a react component; I'd just say to reference this repo in the readme or something.

Cheers,
Sam

**Comment by safeimuslim** [comment]
@SamHerbert thx sam

**Comment by safeimuslim** [comment]
@SamHerbert already released 5 months ago

https://github.com/safeimuslim/react-loading-components
