### ISSUE TITLE
Awesome, but sort of useless.

### ISSUE THREAD

**Issue by xypaul** [SamHerbert/SVG-Loaders#2]
First let me start with saying how awesome these loaders are. Well done :+1: 

But I can't really find use for this loaders. SVG animations only really start to animate once everything is loaded, so they can't really be used as a preloader indicator. Any ideas how I can get around this?\

Thanks,
Paul

**Comment by Waleedov** [comment]
Indeed, the spinners are actually not spinning at all until everything is loaded. What is the point?
Yes, I use inline SVG code.
Is there an update to this?
