### ISSUE TITLE
Pass params when calling

### ISSUE THREAD

**Issue by isbkch** [SamHerbert/SVG-Loaders#7]
I frankly don't know how SVG works but I was wondering since I'm using Bower to include the plugin, and then I'm ignoring the script's folder in Git, I can't change the fill color in the SVG file itself (it won't be pushed with the git commit). I was wondering if I can change the fill from the call, add something like

`<img src="/vendor/svg-loaders/svg-loaders/bars.svg" width="40" alt="" fill="#222" >`

**Comment by SamHerbert** [comment]
The only way to make that work, or manipulate fill from CSS is to remove the fill attribute from the SVG file, which means you'd have to commit it to your project without bower. I don't think there's another way :)
