### ISSUE TITLE
SVG canvas attributes...

### ISSUE THREAD

**Issue by karimbeyrouti** [SamHerbert/SVG-Loaders#9]
Hello Sam, 

Thank you for the lovely SVG icons. 

Quick question - wondering why you have some fill / stroke attributes are on the root SVG tag instead of being in a nested group ? . 

In the following code I moved stroke="#fff" to the group ( from rings.svg ) and it works a treat:

<svg width="45" height="45" viewBox="0 0 45 45" xmlns="http://www.w3.org/2000/svg" >
    <g fill="none" fill-rule="evenodd" transform="translate(1 1)" stroke-width="2" stroke="#fff">
     .....
    </g>
</svg>

For other loaders ( like the grid ) - the fill="#fff" could be part of a nested group . 

Anyway - I was just wondering - as I am importing / loading the loaders into another SVG canvas and that is causing issues. I am quite happy changing your wonderful loaders to suit my needs - but I was wondering if there was a reason. 

Best

**Comment by SamHerbert** [comment]
Hey Karim,

Originally all colors were nested, and that's probably the best way to go about things, but I moved the color to the root element for the ease of people who may download the loaders/not know what's going on in the markup.

Not sure it was the best move... maybe it should be changed.

**Comment by karimbeyrouti** [comment]
The tests with the SVG lib I am working on - we loads your loaders, parse and add them to a custom SVG Canvas. This could very well be an edge use for your lovely loaders. 

Source: https://gist.github.com/karimbeyrouti/852c8c6975940dc1cffb
Demo: http://kurst.co.uk/samples/svgloaders/

This was mainly done as a test for the SVGLoader component. In some cases I re-nested objects in a group to apply a fill / stroke. 

I would say maybe keep it as it is, if you have more designers than developers. I was just curious as to why you had applied it to the SVG tag. 

Thanks Sam.

**Comment by SamHerbert** [comment]
Thanks for the info, karim!

I'll keep it the way it is for the time being, and see if more issues come up. I think many devs will alter that source to best suite their needs.

- Sam
